#!/bin/sh

### testsuite — Run the testsuite for Kaputt

# Kaputt (https://github.com/foretspaisibles/cl-kaputt)
# This file is part of Kaputt.
#
# Copyright © 2019–2021 Michaël Le Barbier
# All rights reserved.

# This software is governed by the CeCILL-B license under French law and
# abiding by the rules of distribution of free software.  You can  use,
# modify and/ or redistribute the software under the terms of the CeCILL-B
# license as circulated by CEA, CNRS and INRIA at the following URL
# "https://cecill.info/licences/Licence_CeCILL-B_V1-en.txt"

: ${LISP:=sbcl --noinform --disable-debugger}

run_all_tests()
{
    local lisp_subsystem
    lisp_subsystem="$1"
    ${LISP}\
	 --eval "(ql:quickload :kaputt/${lisp_subsystem} :silent t)"\
	 --eval "(kaputt/${lisp_subsystem}:run-all-tests-batch)"
}

main()
{
    case "$#-$1" in
	0-)
	    run_all_tests 'testsuite'
	    ;;
	1-testsuite|1-example)
	    run_all_tests "$@"
	    ;;
	*)
	    1>&2 printf 'Error: %s: Nothing is known about this Kaputt subsystem.\n' "$1"
	    return 1
	    ;;
    esac
}

main "$@"

### End of file `testsuite'
