name: Linux

on:
  - push
  - workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v1
    - name: 'Install host SBCL'
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install sbcl libcapstone-dev
